apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  containers:
    - name: postgres
      image: postgres:17
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_DB
          value: appdb
        - name: POSTGRES_USER
          value: appuser
        - name: POSTGRES_PASSWORD
          value: apppassword
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: spring-app-pod
spec:
  containers:
    - name: spring-app
      image: spring-boot-starter-template:latest
      ports:
        - containerPort: 8080
          hostPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-pod:5432/appdb
        - name: SPRING_DATASOURCE_USERNAME
          value: appuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: apppassword
        - name: SPRINGDOC_ENABLE_DATA_REST
          value: "false"